---
# below are all the records necessary for initial setup. Only the "name" in the query has to be updated
init_internal_entries:
  - type: A
    record: "ocp-bastion.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-bastion`].public_v4 | [0]') }}"
    ttl: 60
    state: present
  - type: A
    record: "api.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-lb`].public_v4 | [0]') }}"
    ttl: 60
    state: present
  - type: A
    record: "lb.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-lb`].private_v4 | [0]') }}"
    ttl: 60
    state: present
  - type: A
    record: "*.apps.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-lb`].public_v4 | [0]') }}"
    ttl: 60
    state: present
  - type: A
    record: "api-int.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-lb`].public_v4 | [0]') }}"
    ttl: 60
    state: present

# entries below are required for the bootstrap, this config is applied once the control plane and bootstrap nodes are created    
final_internal_entries:
  - type: A
    record: "bootstrap.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-bootstrap`].private_v4 | [0]') }}"
    ttl: 60
    state: present
  - type: A
    record: "master-0.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-master-0`].private_v4 | [0]') }}"
    ttl: 60
    state: present
  - type: A
    record: "master-1.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-master-1`].private_v4 | [0]') }}"
    ttl: 60
    state: present
  - type: A
    record: "master-2.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-master-2`].private_v4 | [0]') }}"
    ttl: 60
    state: present
  - type: A
    record: "etcd-0.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-master-0`].private_v4 | [0]') }}"
    ttl: 60
    state: present
  - type: A
    record: "etcd-1.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-master-1`].private_v4 | [0]') }}"
    ttl: 60
    state: present
  - type: A
    record: "etcd-2.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-master-2`].private_v4 | [0]') }}"
    ttl: 60
    state: present
  - type: SRV
    record: "_etcd-server-ssl._tcp.{{ guid }}"
    value:
      - "0 0 2380 etcd-0.{{ guid }}"
      - "0 0 2380 etcd-1.{{ guid }}"
      - "0 0 2380 etcd-2.{{ guid }}"
    state: present

# section below configures entries for worker nodes, this config is applied after provisioning of worker nodes
worker_internal_entries:
  - type: A
    record: "worker-0.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-worker-0`].private_v4 | [0]') }}"
    ttl: 60
    state: present
  - type: A
    record: "worker-1.{{ guid }}"
    value: "{{ r_osp_facts | json_query('ansible_facts.openstack_servers[?name==`ocp-worker-1`].private_v4 | [0]') }}"
    ttl: 60
    state: present
