- name: Step 002.0 Post Infrastructure
  hosts: localhost
  connection: local
  become: false
  tags:
  - step002
  - post_infrastructure
  environment:
    OS_AUTH_URL: "{{ osp_auth_url }}"
    OS_USERNAME: "{{ osp_auth_username }}"
    OS_PASSWORD: "{{ osp_auth_password }}"
    OS_PROJECT_NAME: "{{ osp_project_name }}"
    OS_PROJECT_DOMAIN_ID: "{{ osp_auth_project_domain }}"
    OS_USER_DOMAIN_NAME: "{{ osp_auth_user_domain }}"
  tasks:
  - name: debug hostvars
    debug:
      var: hostvars
  - name: debug
    debug:
      var: r_osp_facts
  - name: Create DNS entries for OpenShift FIPs
    debug:
      msg: Currently using {{ osp_cluster_dns_zone }} on server {{ osp_cluster_dns_server }}
    when: openshift_fip_provision

  - set_fact:
      ocp_api_fip: "{{ hot_outputs | json_query(query) }}"
    vars:
      query: "outputs[?@.output_key=='ocp_api_fip'].output_value|[0]"
    when: openshift_fip_provision

  - set_fact:
      ocp_ingress_fip: "{{ hot_outputs | json_query(query) }}"
    vars:
      query: "outputs[?@.output_key=='ocp_ingress_fip'].output_value|[0]"
    when: openshift_fip_provision

  - name: Add DNS entry for OpenShift API and ingress
    nsupdate:
      server: "{{ osp_cluster_dns_server }}"
      zone: "{{ osp_cluster_dns_zone }}"
      record: "{{ item.dns }}.{{ guid }}"
      type: A
      ttl: 5
      value: "{{ item.name }}"
      key_name: "{{ ddns_key_name }}"
      key_algorithm: "{{ ddns_key_algorithm | d('hmac-md5') }}"
      key_secret: "{{ ddns_key_secret }}"
    loop:
      - name: "{{ ocp_api_fip }}"
        dns: "api"
      - name: "{{ ocp_ingress_fip }}"
        dns: "*.apps"
    loop_control:
      label: item.name
    when: openshift_fip_provision

#- name: Step 002.1 Post Infrastructure - Generate and activate the HAproxy configuration
#  hosts: lb_vms
#  tasks:
#  - import_role:
#      name: manage-haproxy
#      tasks_from: install
#    tags:
#    - 'always'
#  - import_role:
#      name: manage-haproxy
#      tasks_from: generate-config
#    tags:
#    - 'always'
#  - import_role:
#      name: manage-haproxy
#      tasks_from: activate-config
#    tags:
#    - 'always'
#
#- name: Step 002.2 Post Infrastructure - Configure web-server
#  hosts: host_www
#  become: true
#  tasks:
#  - import_role:
#      name: config-httpd
