- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  become: false
  tags:
  - step001
  - pre_infrastructure
  tasks:
    - name: Ensure variables are set
      assert:
        that: "{{ item.0 }}"
        msg: "{{ item.1 }}"
      loop:
        - - ocp4_pull_secret is defined
          - ocp4_pull_secret variable must be defined
    - debug:
        msg: "Step 000 Pre Infrastructure - Dummy action"

    - name: set values for instances and stacks variables
      set_fact:
        stacks: "{{ stacks_infra }}"
        instances: "{{ instances_infra }}"
