= Labs OCP 4 Cluster

== Config Description

The following config includes:

* One bastion host for installation
* One web-server and one LB
* One Bootstrap
* Master and Worker nodes
* DNS and other resources for OCP4
* SSH access setup

== Review the `default_vars.yml` variable file

* This file link:./labs_default_vars.yml[./labs_default_vars.yml] contains all the variables you need to define to control the deployment of your environment.

* Override the defaults for your environment by creating your own myenvironment-variables.yml file, as below.

== Review the `labs_vars_osp.yml` variable file

* This file link:./labs_vars_osp.yml[./labs_vars.osp.yml] contains variables you need to define to control the deployment of openstack infrastructure.

== Secrets

secret.yml normally lives in your home direcotry - anywhere outside of the AgnosticD repository itself. They should never be committed to Git!

You will needs to define the `ocp4_pull_secret` variable in order to deploy this config.

Add this variable to your secret file.

* secret.yaml skeleton can be found here link:./secret_skeleton.yaml[./secret_skeleton.yml]. COPY IT TO YOUR HOMEDIR AND EDIT THERE.

[LABS] This might be replaced by RC file. At this point the AgnosticD expects the vars as they are in secret.yaml, unfortunately I didn't find the option to use custom CA in secret.yaml so you have to export your OS_CACERT as well.

[source,yaml]
----
ocp4_pull_secret: '{"auths":{"cloud.openshift.com":{"auth":"...","email":"..."},"quay.io":{"auth":"...","email":"..."},"registry.connect.redhat.com":{"auth":"...","email":"..."},"registry.redhat.io":{"auth":"...","email":"..."}}}'
----

=== Running Playbook With Environment and Secrets files

You can create yaml files of your desired configs and secrets and execute them from agnosticd directory:

`ansible-playbook ansible/main.yaml -e @myenvironment-variables.yml  -e@my-secrets.yml`

== Workstation Setup:
[LABS] here we might use container in the future instead of  setting up localhost

With either setup, you also need to have a `clouds.yaml` file on your system with credentials.
You can store this either in your working directory or in `~/.config/openstack/clouds.yaml`.

[LABS]Clouds.yaml is still required at this point because it is used on the bastion host to execute openstack commands. This will be converted to rc files going forward

=== RHEL:

To prepare an admin host to deploy this config. This has been tested on RHEL 7.7.
sudo subscription-manager register
sudo subscription-manager attach --pool=<yourpool>
sudo subscription-manager repos --disable=* --enable rhel-7-server-optional-rpms \
  --enable rhel-7-server-rpms --enable rhel-7-server-extras-rpms

sudo yum update -y

sudo yum install python-virtualenv git gcc

git clone https://github.com/redhat-cop/agnosticd.git
cd agnosticd
git checkout disco-ocp4

virtualenv ~/venv-openstack
source ~/venv-openstack/bin/activate

pip install -r ./ansible/configs/ocp4-disconnected-ha-lab/files/admin_host_requirements.txt


=== MacOS:
# Install python3:
brew install python

# Make sure your path has this in it:
PATH="/usr/local/opt/python/libexec/bin:/usr/local/bin:$PATH"

# Make sure virtualenv and virtualenvwrapper are installed system wide
pip install virtualenv
pip install virtualenvwrapper

# Add this to your .bashrc
export WORKON_HOME=~/.virtualenvs
[ -f /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh

# To start a new python virtual env
mkvirtualenv venv-openstack

# Activate virtual env
workon venv-openstack

# Clone repo and install python libraries
git clone https://github.com/redhat-cop/agnosticd.git
cd agnosticd
git checkout disco-ocp4
pip install -r ./ansible/configs/ocp4-disconnected-ha-lab/files/macos_requirements.txt



User access:
student_name is defined either in sample_vars or from deployer script. This is the account that people will use and will generally match their opentlc ID. lab-user is the default defined in the role

