= Labs OCP 4 Cluster

== Config Description

The following config includes:

* One bastion host for installation
* One web-server and one LB
* One Bootstrap
* Master and Worker nodes
* DNS and other resources for OCP4
* SSH access setup

== Review the `labs_default_vars.yml` variable file

* This file link:./labs_default_vars.yml[./labs_default_vars.yml] contains all the variables you need to define to control the deployment of your environment.

* Override the defaults for your environment by creating your own myenvironment-variables.yml file, as below.

== Review the `labs_vars_osp.yml` variable file

* This file link:./labs_vars_osp.yml[./labs_vars.osp.yml] contains variables you need to define to control the deployment of openstack infrastructure.

== Secrets

secret.yml normally lives in your home direcotry - anywhere outside of the AgnosticD repository itself. They should never be committed to Git!

You will needs to define the `ocp4_pull_secret` variable in order to deploy this config.

Add this variable to your secret file.

* secret.yaml skeleton can be found here link:./secret_skeleton.yaml[./secret_skeleton.yml]. COPY IT TO YOUR HOMEDIR AND EDIT THERE.

[LABS] This might be partially replaced by RC file. At this point the AgnosticD expects the vars as they are in secret.yaml, unfortunately I didn't find the option to use custom CA in secret.yaml so you have to export your OS_CACERT as well.

[source,yaml]
----
ocp4_pull_secret: '{"auths":{"cloud.openshift.com":{"auth":"...","email":"..."},"quay.io":{"auth":"...","email":"..."},"registry.connect.redhat.com":{"auth":"...","email":"..."},"registry.redhat.io":{"auth":"...","email":"..."}}}'
----

=== Running Playbook With Environment and Secrets files

You can create yaml files of your desired configs and secrets and execute them from agnosticd directory:

`ansible-playbook ansible/main.yaml -e @myenvironment-variables.yml  -e@my-secrets.yml`

== Workstation Setup:
[LABS] here we might use container in the future instead of  setting up localhost

You also need to source the rc file for the environment. The current AgnosticD doesn't support OS_CACERT variable in the secret.yml

install required packages
git clone https://github.com/redhat-cop/agnosticd.git cd agnosticd git checkout disco-ocp4
pip install -r ./ansible/configs/ocp4-disconnected-ha-lab/files/admin_host_requirements.txt

More detailed env_setup section is ocp4-cluster config
