---
- name: Step 001 software
  hosts: bastions
  gather_facts: false
  become: true
  tasks:
  - name: Debug
    debug:
      msg: "Software playbook"

- name: Step 004.1 - Host preparation for OpenShift 4 deployment
  hosts: bastions
  become: true
  gather_facts: False
  tags:
    - step004
    - step004.1
  tasks:
  - name: Call Role to provision OCP4 install host
    include_role:
      name: host-ocp4-provisioner

- name: Step 004.2 Prepare ignition files for Openshift installation
  hosts: bastions
  gather_facts: false
  become: false
  tags:
    - step004
    - step004.2
  tasks:
  - name: Call Role to install OpenShift
    when: install_ocp4 | d(True) | bool
    include_role:
      name: host-ocp4-installer

- name: Step 004.3 configure web_server Openshift installation
  hosts: host_www
  become: true
  tags:
    - step004
    - step004.3
  tasks:
  - name: Call Role to install the web_server
    when: install_ocp4 | d(True) | bool
    include_role:
      name: config-httpd

- name: step 004.4 create the user-data
  hosts: localhost
  become: false
  tasks:
  - name: create user-data
    template:
      src: files/user-data.j2
      dest: /tmp/output_dir/{{ item }}
    loop:
    - worker
    - master
    - bootstrap
